name: navigation_drawer_menu_example
description: navigation_drawer_menu Example

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.0-377.8.beta <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  navigation_drawer_menu:
    path: ..

dev_dependencies:
  dart_code_metrics: ^4.16.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
