name: navigation_drawer_menu
description: Flutter Material Design Navigation Drawer Menu. This package gives you the NavigationDrawerMenu widget which acts like a ListView. The example implements the full Navigation Drawer.
version: 0.2.0-beta
homepage: https://github.com/MelbourneDeveloper/navigation_drawer_menu

environment:
  sdk: ">=2.14.0-377.8.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material: ^1.0.0+2

dev_dependencies:
  dart_code_metrics: ^4.16.0
  lints: ^1.0.1
  pedantic: ^1.11.1
  test:
